[buildPlans.IosevkaSharpie]
family = "Iosevka Sharpie"
desc = "Default"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = true
webfontFormats = ["ttf", "woff2"]

[buildPlans.IosevkaSharpie.variants.design]
l = "serifed-flat-tailed"
lower-delta = "flat-top"
lower-xi = "flat-top"
zero = "dotted"
one = "base"
three = "flat-top"
asterisk = "penta-low"
brace = "curly-flat-boundary"
percent = "rings-continuous-slash"
pilcrow = "low"

[buildPlans.IosevkaSharpie.ligations]
inherits = "dlig"

[buildPlans.IosevkaSharpie.widths]
Normal = { shape = 500, menu = 5, css = "normal" }
Extended = { shape = 600, menu = 7, css = "expanded" }
Condensed = { shape = 416, menu = 3, css = "condensed" }

[buildPlans.IosevkaSharpieTerm]
family = "Iosevka Sharpie Term"
spacing = "term"
serifs = "sans"
# noCvSs = false
exportGlyphNames = true

[buildPlans.IosevkaSharpieTerm.variants]
inherits = "buildPlans.IosevkaSharpie"

[buildPlans.IosevkaSharpieTerm.widths]
Normal = { shape = 500, menu = 5, css = "normal" }
Extended = { shape = 600, menu = 7, css = "expanded" }
Condensed = { shape = 416, menu = 3, css = "condensed" }

[buildPlans.IosevkaSharpieFixed]
family = "Iosevka Sharpie Fixed"
spacing = "fixed"
serifs = "sans"
# noCvSs = false
exportGlyphNames = true

[buildPlans.IosevkaSharpieFixed.variants]
inherits = "buildPlans.IosevkaSharpie"

[buildPlans.IosevkaSharpieFixed.widths]
Normal = { shape = 500, menu = 5, css = "normal" }
Extended = { shape = 600, menu = 7, css = "expanded" }
Condensed = { shape = 416, menu = 3, css = "condensed" }

[buildPlans.IosevkaSharpieAile]
family = "Iosevka Sharpie Aile"
desc = "Sans-serif"
spacing = "quasi-proportional"
# noCvSs = false
exportGlyphNames = true

[buildPlans.IosevkaSharpieAile.variants]
inherits = "buildPlans.IosevkaAile"

[buildPlans.IosevkaSharpieAile.variants.design]
zero = "dotted"
# capital-i = "serifless"
# capital-j = "serifless"
# capital-k = "straight-serifless"
# capital-m = "flat-bottom-serifless"
# capital-w = "straight-flat-top-serifless"
# a = "double-storey-serifless"
# d = "toothed-serifless"
# e = "flat-crossbar"
# f = "flat-hook-serifless"
# g = "single-storey-serifless"
# i = "serifless"
# j = "flat-hook-serifless"
# k = "straight-serifless"
# l = "serifless"
# r = "compact-serifless"
# t = "flat-hook"
# u = "toothed-serifless"
# w = "straight-flat-top-serifless"
# y = "straight-serifless"
# long-s = "flat-hook-serifless"
# eszet = "longs-s-lig-serifless"
# lower-iota = "flat-tailed"
# lower-lambda = "straight-turn"
# lower-tau = "flat-tailed"
# cyrl-capital-ka = "symmetric-connected-serifless"
# cyrl-ka = "symmetric-connected-serifless"
# cyrl-em = "flat-bottom-serifless"
# cyrl-capital-u = "straight-serifless"
# cyrl-u = "straight-serifless"
# cyrl-ef = "serifless"
# cyrl-yeri = "corner"
# cyrl-yery = "corner"
# at = "fourfold"
# percent = "rings-continuous-slash"
# micro-sign = "toothed-serifless"

[buildPlans.IosevkaSharpieAile.derivingVariants.mathtt.design]
zero = "dotted"
# capital-i = "serifed"
# capital-j = "serifless"
# capital-k = "straight-serifless"
# capital-m = "flat-bottom-serifless"
# capital-w = "straight-flat-top-serifless"
# a = "double-storey-serifless"
# d = "toothed-serifless"
# e = "flat-crossbar"
# f = "flat-hook-serifless"
# g = "single-storey-serifless"
# i = "serifed"
# j = "flat-hook-serifed"
# k = "straight-serifless"
# l = "serifed"
# r = "compact-serifless"
# t = "flat-hook"
# u = "toothed-serifless"
# w = "straight-flat-top-serifless"
# y = "straight-serifless"
# long-s = "flat-hook-serifless"
# eszet = "longs-s-lig-serifless"
# lower-iota = "serifed-flat-tailed"
# lower-lambda = "straight-turn"
# lower-tau = "flat-tailed"
# cyrl-capital-ka = "symmetric-connected-serifless"
# cyrl-ka = "symmetric-connected-serifless"
# cyrl-em = "flat-bottom-serifless"
# cyrl-capital-u = "straight-serifless"
# cyrl-u = "straight-serifless"
# cyrl-ef = "serifless"
# cyrl-yeri = "corner"
# cyrl-yery = "corner"
# at = "fourfold"
# percent = "rings-continuous-slash"
# micro-sign = "toothed-serifless"

[buildPlans.IosevkaSharpieAile.widths]
Normal = { shape = 600, menu = 5, css = "normal" }

[buildPlans.IosevkaSharpieEtoile]
family  = "Iosevka Sharpie Etoile"
desc = "Slab-serif"
spacing = "quasi-proportional"
serifs = 'slab'
# noCvSs = false
exportGlyphNames = true

[buildPlans.IosevkaSharpieEtoile.variants]
inherits = "buildPlans.IosevkaEtoile"

[buildPlans.IosevkaSharpieEtoile.variants.design]
zero = "dotted"

[buildPlans.IosevkaSharpieEtoile.variants.italic]
zero = "dotted"

[buildPlans.IosevkaSharpieEtoile.widths]
Normal = { shape = 600, menu = 5, css = "normal" }

[collectPlans.IosevkaSharpie]
from = [
  "IosevkaSharpie",
  "IosevkaSharpieTerm",
  "IosevkaSharpieFixed"
]

[collectPlans.IosevkaSharpieAile]
from = ["IosevkaSharpieAile"]

[collectPlans.IosevkaSharpieEtoile]
from = ["IosevkaSharpieEtoile"]
