[buildPlans.iosevka-sharpie]
family = "Iosevka Sharpie"
desc = "Default"
spacing = "normal"
serifs = "sans"
no-cv-ss = false
export-glyph-names = true

[buildPlans.iosevka-sharpie.ligations]
inherits = "dlig"

[buildPlans.iosevka-sharpie.variants.design]
l = "serifed-flat-tailed"
lower-delta = "flat-top"
lower-xi = "flat-top"
zero = "dotted"
one = "base"
three = "flat-top"
asterisk = "penta-low"
brace = "curly-flat-boundary"
percent = "rings-continuous-slash"
pilcrow = "low"

[buildPlans.iosevka-sharpie.widths]
normal = { shape = 500, menu = 5, css = "normal" }
extended = { shape = 600, menu = 7, css = "expanded" }
condensed = { shape = 416, menu = 3, css = "condensed" }

[buildPlans.iosevka-sharpie-term]
family = "Iosevka Sharpie Term"
spacing = "term"
serifs = "sans"
# no-cv-ss = false
export-glyph-names = true

[buildPlans.iosevka-sharpie-term.variants]
inherits = "buildPlans.iosevka-sharpie"

[buildPlans.iosevka-sharpie-term.widths]
normal = { shape = 500, menu = 5, css = "normal" }
extended = { shape = 600, menu = 7, css = "expanded" }
condensed = { shape = 416, menu = 3, css = "condensed" }

[buildPlans.iosevka-sharpie-fixed]
family = "Iosevka Sharpie Fixed"
spacing = "fixed"
serifs = "sans"
# no-cv-ss = false
export-glyph-names = true

[buildPlans.iosevka-sharpie-fixed.variants]
inherits = "buildPlans.iosevka-sharpie"

[buildPlans.iosevka-sharpie-fixed.widths]
normal = { shape = 500, menu = 5, css = "normal" }
extended = { shape = 600, menu = 7, css = "expanded" }
condensed = { shape = 416, menu = 3, css = "condensed" }

[buildPlans.iosevka-sharpie-aile]
family = "Iosevka Sharpie Aile"
desc = "Sans-serif"
spacing = "quasi-proportional"
# no-cv-ss = false
export-glyph-names = true

[buildPlans.iosevka-sharpie-aile.variants]
inherits = "buildPlans.iosevka-aile"

[buildPlans.iosevka-sharpie-aile.variants.design]
zero = "dotted"
# capital-i = "serifless"
# capital-j = "serifless"
# capital-k = "straight-serifless"
# capital-m = "flat-bottom-serifless"
# capital-w = "straight-flat-top-serifless"
# a = "double-storey-serifless"
# d = "toothed-serifless"
# e = "flat-crossbar"
# f = "flat-hook-serifless"
# g = "single-storey-serifless"
# i = "serifless"
# j = "flat-hook-serifless"
# k = "straight-serifless"
# l = "serifless"
# r = "compact-serifless"
# t = "flat-hook"
# u = "toothed-serifless"
# w = "straight-flat-top-serifless"
# y = "straight-serifless"
# long-s = "flat-hook-serifless"
# eszet = "longs-s-lig-serifless"
# lower-iota = "flat-tailed"
# lower-lambda = "straight-turn"
# lower-tau = "flat-tailed"
# cyrl-capital-ka = "symmetric-connected-serifless"
# cyrl-ka = "symmetric-connected-serifless"
# cyrl-em = "flat-bottom-serifless"
# cyrl-capital-u = "straight-serifless"
# cyrl-u = "straight-serifless"
# cyrl-ef = "serifless"
# cyrl-yeri = "corner"
# cyrl-yery = "corner"
# at = "fourfold"
# percent = "rings-continuous-slash"
# micro-sign = "toothed-serifless"

[buildPlans.iosevka-sharpie-aile.derivingVariants.mathtt.design]
zero = "dotted"
# capital-i = "serifed"
# capital-j = "serifless"
# capital-k = "straight-serifless"
# capital-m = "flat-bottom-serifless"
# capital-w = "straight-flat-top-serifless"
# a = "double-storey-serifless"
# d = "toothed-serifless"
# e = "flat-crossbar"
# f = "flat-hook-serifless"
# g = "single-storey-serifless"
# i = "serifed"
# j = "flat-hook-serifed"
# k = "straight-serifless"
# l = "serifed"
# r = "compact-serifless"
# t = "flat-hook"
# u = "toothed-serifless"
# w = "straight-flat-top-serifless"
# y = "straight-serifless"
# long-s = "flat-hook-serifless"
# eszet = "longs-s-lig-serifless"
# lower-iota = "serifed-flat-tailed"
# lower-lambda = "straight-turn"
# lower-tau = "flat-tailed"
# cyrl-capital-ka = "symmetric-connected-serifless"
# cyrl-ka = "symmetric-connected-serifless"
# cyrl-em = "flat-bottom-serifless"
# cyrl-capital-u = "straight-serifless"
# cyrl-u = "straight-serifless"
# cyrl-ef = "serifless"
# cyrl-yeri = "corner"
# cyrl-yery = "corner"
# at = "fourfold"
# percent = "rings-continuous-slash"
# micro-sign = "toothed-serifless"

[buildPlans.iosevka-sharpie-aile.widths]
normal = { shape = 600, menu = 5, css = "normal" }

[buildPlans.iosevka-sharpie-etoile]
family  = "Iosevka Sharpie Etoile"
desc = "Slab-serif"
spacing = "quasi-proportional"
serifs = 'slab'
# no-cv-ss = false
export-glyph-names = true

[buildPlans.iosevka-sharpie-etoile.variants]
inherits = "buildPlans.iosevka-etoile"

[buildPlans.iosevka-sharpie-etoile.variants.design]
zero = "dotted"

[buildPlans.iosevka-sharpie-etoile.variants.italic]
zero = "dotted"

[buildPlans.iosevka-sharpie-etoile.widths]
normal = { shape = 600, menu = 5, css = "normal" }

[collectPlans.iosevka-sharpie]
from = [
  "iosevka-sharpie",
  "iosevka-sharpie-term",
  "iosevka-sharpie-fixed"
]

[collectPlans.iosevka-sharpie-aile]
from = ["iosevka-sharpie-aile"]

[collectPlans.iosevka-sharpie-etoile]
from = ["iosevka-sharpie-etoile"]
